
@php 

use App\Helpers\QlikHelper as HelpersQlikHelper;
use App\Http\Controllers\System\QlikAppController;
use App\Helpers\CRUDBooster;

$conf = QlikAppController::getConf($qlik_conf);
//generate a random string
$state = bin2hex(random_bytes(16));

$token = '';
$token3 = '';
$src = '';
$css = '';

if ($conf->type == 'SAAS') {
  $token = HelpersQlikHelper::getJWTToken(CRUDBooster::myId(), $conf->id);
  $src = $conf->host . "/resources/assets/external/requirejs/require.js?state=$state";
  $css = $conf->host . "/resources/autogenerated/qlik-styles.css";
} 


if ($conf->type == 'On-Premise' && $conf->auth == 'JWT') {
  $token = HelpersQlikHelper::getJWTTokenOP(CRUDBooster::myId(), $conf->id);
  $src =  "resources/assets/external/requirejs/require.js?state=$state";
  $css = "resources/autogenerated/qlik-styles.css";

  
} 
// Modalità Ticket: non più supportata (nascosta nel form di configurazione).
// Le funzioni helper non esistono più: si chiamano solo se presenti, per non
// andare in errore fatale su una conf legacy.
if ($conf->type == 'On-Premise' && $conf->auth == 'Ticket'
    && method_exists(HelpersQlikHelper::class, 'getTicketFromConf')) {

  //in realta sarebbe il ticket
  $token = HelpersQlikHelper::getTicketFromConf($conf->id);
  $token3 = $token;
  $data_ticket = HelpersQlikHelper::dataForTicketConf($conf->id);
  $src =  "resources/assets/external/requirejs/require.js?qlikTicket=".$token;
  $css = "resources/autogenerated/qlik-styles.css?qlikTicket=".$token;
}

$js_defer = $conf->type == "On-Premise" ? "js/qlik_login_widget_objop" : "js/qlik_login_widget_obj";

$js_defer = ($conf->auth == "Ticket" && $conf->type == "On-Premise") ? "js/qlik_login_widget_objopticket" : $js_defer;

@endphp
@if (isset($conf) && $conf) 
<!DOCTYPE html>
<html>
<head>
<script  type="text/javascript" >

var type = {!! json_encode((string) $conf->type) !!};
var qlik_token = {!! json_encode($conf->auth == "JWT" ? (string) $token : "") !!};
@if ($conf->type == 'On-Premise' && $conf->auth == "Ticket")
var qlik_ticket = {!! json_encode($conf->type == "On-Premise" && $conf->auth == "Ticket" ? (string) $token : "") !!};
var qlik_ticket3 = {!! json_encode($conf->type == "On-Premise" && $conf->auth == "Ticket" ? (string) $token3 : "") !!};
@endif
var src_js = {!! json_encode((string) $src) !!};

@if ($conf->type == 'On-Premise' && $conf->auth == "Ticket")
var ticket_data = {!! json_encode(isset($data_ticket) ? (string) $data_ticket : "") !!};
@endif

var host = {!! json_encode((string) $conf->host) !!};
var prefix = {!! json_encode((string) $conf->prefix) !!};
var port = {!! json_encode((string) $conf->port) !!};
var webIntegrationId = {!! json_encode((string) $conf->webIntegrationId) !!};
var QLIK_I18N = {!! json_encode(['current_selections' => trans('crudbooster.qlik_current_selections')]) !!};
var appId = {!! json_encode((string) $mashup->appid) !!};
var mashupId = {!! json_encode((string) $mashup->id) !!};
var objectid = {!! json_encode((string) $config->object) !!};

var hidden_object = parent.document.getElementById('mashup_object_hidden');
var hidden_app = parent.document.getElementById('mashup_app_hidden');



</script>
<script type="text/javascript"  src="{{asset($js_defer)}}.js"></script>

</head>

<body>

  <div id="{{$mashup->appid}}" >


  <div id="title">{!! __('crudbooster.qlik_app_loading') !!}</div>

<input type="hidden" id="state_page" name="state_page">

  </div>

@endif
</body>


</html>

