@php

use App\Helpers\QlikHelper as HelpersQlikHelper;
use App\Http\Controllers\System\QlikAppController;
use App\Helpers\CRUDBooster;

$conf = QlikAppController::getConf($qlik_conf);


$state = bin2hex(random_bytes(16));

if ($conf->auth == 'JWT' && $conf->type == 'SAAS') {
  $token = HelpersQlikHelper::getJWTToken(CRUDBooster::myId(), $conf->id);
} else {
  $token = HelpersQlikHelper::getJWTTokenOP(CRUDBooster::myId(), $conf->id);
}
$src = "resources/assets/external/requirejs/require.js?state=$state";
$css = "resources/autogenerated/qlik-styles.css";

if (!isset($mashups->object)) {
  $mashups->object = "object";
}

@endphp 
@if (isset($conf) && $conf) 

<link rel="stylesheet" href="{{ $css }}">

<!--
<script type="text/javascript"  src="{{$src}}"></script>
-->


<div id="{{$mashup->appid}}" >
<script  type="text/javascript" >

var type = {!! json_encode((string) $conf->type) !!};
//var qlik_token = '{{$conf->type == "SAAS" ? $token : ""}}';
var qlik_token = {!! json_encode((string) $token) !!};
var qlik_ticket = {!! json_encode($conf->type == "On-Premise" ? (string) $token : "") !!};
var src_js = {!! json_encode((string) $src) !!};
var src = {!! json_encode((string) $src) !!};

@if ($conf->type == 'On-Premise')
var ticket_data = {!! json_encode(isset($data_ticket) ? (string) $data_ticket : "") !!};
@endif

var host = {!! json_encode((string) $conf->host) !!};
var prefix = {!! json_encode((string) $conf->prefix) !!};
var port = {!! json_encode((string) $conf->port) !!};
var webIntegrationId = {!! json_encode((string) $conf->webIntegrationId) !!};
var QLIK_I18N = {!! json_encode(['object_loading' => trans('crudbooster.qlik_object_loading')]) !!};
var appId = {!! json_encode((string) $mashup->appid) !!};
var mashupId = {!! json_encode((string) $mashup->id) !!};
var objectid = {!! json_encode((string) $mashups->object) !!};
</script>


  <div id="title" role="status" aria-live="polite">{{ trans('crudbooster.qlik_app_loading') }}</div>

<div id="{{$mashups->object}}"></div>

<div class="text-danger" ></div>
</div>
<script defer  src="{{asset('js/qlik_login_widget.js')}}"></script>
@endif
