@php

use crocodicstudio\crudbooster\helpers\QlikHelper as HelpersQlikHelper;
use crocodicstudio\crudbooster\controllers\QlikMashupController;
use crocodicstudio\crudbooster\helpers\CRUDBooster;

$conf = QlikMashupController::getConf($qlik_conf);
//$token = HelpersQlikHelper::getJWTToken(CRUDBooster::myId(), $conf->id);
$state = bin2hex(random_bytes(16));


if ($conf->type == 'SAAS') {
  $token = HelpersQlikHelper::getJWTToken(CRUDBooster::myId(), $conf->id);
  $src = $conf->host . "/resources/assets/external/requirejs/require.js?state=$state";
  $css = $conf->host . "/resources/autogenerated/qlik-styles.css";
} else {

  //in realta sarebbe il ticket
  $token = HelpersQlikHelper::getTicketFromConf($conf->id) ;
  $data_ticket = HelpersQlikHelper::dataForTicketConf($conf->id);
  $src = $conf->host . "/resources/assets/external/requirejs/require.js?state=$state&qlikTicket=".$token;
  $css = $conf->host . "/resources/autogenerated/qlik-styles.css?qlikTicket=".$token;
}

/*
if ($conf->type == 'SAAS') {
  $token = HelpersQlikHelper::getJWTToken(CRUDBooster::myId(), $conf->id);
  $src = $conf->host . "/resources/assets/external/requirejs/require.js";
} else {

  //in realta sarebbe il ticket
  $token = HelpersQlikHelper::getTicketFromConf($conf->id) ;
  $src = $conf->host . "/resources/assets/external/requirejs/require.js?qlikTicket=$token";
}
*/

$js_defer = $conf->type == "On-Premise" ? "js/qlik_login_widget_objop.js" : "js/qlik_login_widget_obj.js";

$param = $conf->type == 'On-Premise' ? "?qlikTicket=$token" : "";

@endphp 
@if (isset($conf) && $conf) 

<link rel="stylesheet" href="{{ $css }}">

<script type="text/javascript"  src="{{$src}}"></script>



<div id="{{$mashup->appid}}" >
<script  type="text/javascript" >

console.log("css");
console.log("{{$css}}");

console.log("src");
console.log("{{$src}}");

var type = '{{$conf->type}}';
console.log("type");
console.log(type);

var qlik_token = '{{$conf->type == "SAAS" ? $token : ""}}';
console.log("qlik_token");
console.log(qlik_token);

var qlik_ticket = '{{$conf->type == "On-Premise" ? $token : ""}}';
console.log("qlik_ticket");
console.log(qlik_ticket);

var src_js = "@php echo $src  @endphp";
console.log("src_js");
console.log(src_js);

@if ($conf->type == 'On-Premise')

var ticket_data = @php echo isset($data_ticket) ? $data_ticket : "" @endphp;
console.log("ticket_data");
console.log(ticket_data);

@endif


var host = '{{$conf->host}}';
console.log("host");
console.log(host);

var prefix = '{{$conf->prefix}}';
console.log("prefix");
console.log(prefix);


var port = '{{$conf->port}}';
console.log("port");
console.log(port);

var webIntegrationId = '{{$conf->webIntegrationId}}';

console.log("webIntegrationId");
console.log(webIntegrationId);
var appId = '{{$mashup->appid}}';
console.log("appId");
console.log(appId);

var mashupId = '{{$mashup->id}}';
console.log("mashupId");
console.log(mashupId);

var objectid = '{{$config->object}}';
console.log("objectid");
console.log(objectid);
</script>


  <div id="title">Loading Qlik App. Please wait.</div>

<div id="{{$mashups->object}}"></div>

<div class="text-danger" ></div>
</div>
<script defer  src="{{asset('js/qlik_login_widget.js')}}"></script>
@endif
