version: '3.8'

networks:
  laravel:
    driver: bridge

services:
  # Servizio Applicazione Laravel
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: CustomerHive
    volumes:
      #- ./:/var/www/html
      #- chive-volumes:/var/www/html/storage
      - chive-volumes:/var/www/html/app/Http/Controllers
    #entrypoint: sh -c "sleep 30 && php /var/www/html/artisan migrate && php /var/www/html/artisan db:seed"

    ports:
      - "80:80"
    depends_on:
      - database
      #database:
      #  condition: service_healthy
    restart: unless-stopped
    networks:
      - laravel
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: chive_staging
      DB_USERNAME: chive_user
      DB_PASSWORD: chive_password

  # Servizio Database MySQL
  database:
    image: mysql:8.0
    container_name: database
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chive_staging
      MYSQL_USER: chive_user
      MYSQL_PASSWORD: chive_password
    restart: unless-stopped
    networks:
      - laravel
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5

  # Servizio Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:8080" 
    depends_on:
      - database
      #database:
      #  condition: service_healthy
    networks:
      - laravel 

volumes:
  mysql-data:
    driver: local
  chive-volumes:
    driver: local