<?php

namespace App\Dashboards;

use App\Helpers\ModuleHelper;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Fase 0/2 del piano "dashboard a griglia libera" (vedi
 * docs/piano-dashboard-griglia-libera.md, docs/refactoring/108 e 110).
 * Estesa in docs/refactoring/131-* con la generazione automatica dei
 * dataset dallo schema reale del DB.
 *
 * Elenco dei dataset offerti al "query builder guidato" della griglia -
 * alternativa alla SQL libera gia' esistente nei widget
 * (StatisticBuilderController::getViewComponent()), non un sostituto: chi
 * la sa scrivere continua a poter usare SQL diretta.
 *
 * Due fonti, unite in all():
 * - curated(): dataset scritti a mano (comportamento originale, invariato)
 *   quando serve un controllo fine su etichette/metriche specifiche.
 * - autoGenerated(): un dataset per ogni tabella reale del DB non esclusa
 *   dalle regole sotto, con metriche/dimensioni/filtri dedotti dal tipo
 *   delle colonne (introspezione via information_schema, mai da input
 *   dell'utente finale).
 *
 * La sicurezza NON sta piu' in un elenco di sole 2 tabelle scritte a
 * mano, ma in tre regole applicate all'introspezione:
 * 1. TABLE_DENYLIST: tabelle di sistema/sicurezza mai esposte (token,
 *    licenza, MFA, coda email, config con eventuali password...).
 * 2. Le tabelle `cms_*` (ossatura interna di CRUDBooster: moduli, menu,
 *    privilegi, dashboard-meta) sono escluse di default, salvo la piccola
 *    CMS_TABLE_ALLOWLIST esplicita.
 * 3. COLUMN_DENYLIST_PATTERNS: qualunque colonna il cui nome somiglia a
 *    una credenziale (password/token/secret/...) e' esclusa da qualunque
 *    tabella restante, anche solo come filtro o raggruppamento - perche'
 *    un widget costruito da un superadmin puo' finire su una dashboard
 *    visibile anche a ruoli meno privilegiati (vedi 091): il rischio non
 *    e' "chi puo' costruire la query" ma "quali valori grezzi finiscono
 *    visibili in un'etichetta di un grafico condiviso".
 *
 * Solo colonne/tabelle/aggregazioni passate da queste regole possono
 * finire in una query eseguita; execute() le riverifica comunque ad ogni
 * chiamata (mai fidarsi soltanto di cio' che la UI ha mostrato).
 *
 * Per un cliente specifico, dataset curati aggiuntivi si aggiungono in
 * curated() (o in una classe dedicata sotto questo stesso namespace)
 * seguendo lo stesso pattern gia' usato per moduli/controller custom per
 * cliente.
 */
class DashboardDatasetRegistry
{
    private const TABLE_DENYLIST = [
        'migrations', 'password_resets', 'personal_access_tokens', 'license',
        'cms_apikey', 'cms_apicustom', 'cms_settings', 'cms_email_queues',
        'cms_email_templates', 'mfa_email_otp_codes', 'mfa_recovery_codes',
        'mfa_recovery_requests', 'mfa_trusted_devices', 'chat_ai_history',
        'qlik_confs', 'chatai_confs', 'log',
    ];

    /**
     * Tabelle `cms_*` ammesse nonostante la regola generale che le esclude
     * (sono dati di business, non ossatura interna di CRUDBooster).
     */
    private const CMS_TABLE_ALLOWLIST = ['cms_users', 'cms_logs', 'cms_notifications'];

    private const COLUMN_DENYLIST_PATTERNS = [
        'password', 'token', 'secret', 'api_key', 'apikey', 'hash', 'otp',
        'credential', 'private_key',
    ];

    private const DATE_TYPES = ['date', 'datetime', 'timestamp'];

    /**
     * Tipi MySQL (information_schema.columns.DATA_TYPE) trattati come
     * "numerici" per generare le metriche di aggregazione extra
     * (docs/refactoring/138-*) e per scegliere gli operatori di filtro
     * adatti alla colonna (punto 3 della richiesta utente). Include anche
     * `tinyint` (spesso usato come flag 0/1, es. `pagata`): sommare un
     * flag e' un caso limite ma legittimo ("quante righe true"), non vale
     * la pena distinguerlo da un tinyint numerico vero - DATA_TYPE da solo
     * non lo permetterebbe comunque senza un'altra query su
     * information_schema per leggere anche la lunghezza della colonna.
     */
    private const NUMERIC_TYPES = [
        'int', 'bigint', 'smallint', 'mediumint', 'tinyint', 'decimal', 'float', 'double',
    ];

    /**
     * Aggregazioni extra generate per ogni colonna numerica di un dataset
     * auto-generato, in aggiunta al "Conteggio righe" sempre presente
     * (docs/refactoring/138-*, punto 1 della richiesta utente - erano gia'
     * presenti prima di 133, tolte li' per semplificare finche' non fosse
     * servito altro).
     */
    private const NUMERIC_METRIC_AGGREGATIONS = [
        'sum' => 'Somma',
        'avg' => 'Media',
        'min' => 'Minimo',
        'max' => 'Massimo',
    ];

    /**
     * Operatori di filtro ammessi per categoria di colonna
     * (docs/refactoring/138-*, punto 3): whitelist server-side, non ci si
     * fida del fatto che la UI mostri solo operatori "adatti" al tipo -
     * execute() la riverifica sempre. 'last_days' (punto 4, "ultimi N
     * giorni") ha senso solo su colonne data/datetime/timestamp.
     */
    private const OPERATORS_BY_TYPE = [
        'numeric' => ['=', '!=', '>', '<', '>=', '<='],
        'text' => ['=', '!=', 'contains'],
        // >/</>=/<= aggiunti in docs/refactoring/153-* (richiesta diretta
        // dell'utente): prima una colonna data offriva solo uguaglianza e
        // "ultimi N giorni", nessun modo di dire "prima/dopo il ...".
        'date' => ['=', '!=', '>', '<', '>=', '<=', 'last_days'],
    ];

    /**
     * Granularita' offerte per raggruppare una colonna data/datetime/
     * timestamp (docs/refactoring/151-*, punto "Raggruppa per" separato
     * in Colonna + Formato - stessa idea di Funzione+Colonna per le
     * metriche in 140). 'year' e' nuovo: prima si generavano solo
     * month/day. L'ordine qui e' quello mostrato nella select "Formato".
     */
    private const DATE_DIMENSION_FORMATS = [
        'day' => 'crudbooster.statistic_builder_date_format_day',
        'month' => 'crudbooster.statistic_builder_date_format_month',
        // docs/refactoring/154-*: solo il mese (01..12), senza anno -
        // permette di sovrapporre anni diversi sullo stesso grafico.
        'month_of_year' => 'crudbooster.statistic_builder_date_format_month_of_year',
        'year' => 'crudbooster.statistic_builder_date_format_year',
    ];

    private static ?array $cache = null;

    /**
     * @return array<string, array{
     *   label: string,
     *   table: string,
     *   metrics: array<string, array{label: string, column: string, aggregation: string}>,
     *   dimensions: array<string, string>,
     *   filters: array<string, string>,
     * }>
     */
    public static function all(): array
    {
        if (self::$cache !== null) {
            return self::$cache;
        }

        return self::$cache = array_merge(self::curated(), self::autoGenerated());
    }

    private static function curated(): array
    {
        return [
            'admin_users' => [
                'label' => 'Utenti amministratori',
                'table' => 'cms_users',
                'metrics' => [
                    'count' => ['label' => 'Numero utenti', 'column' => 'id', 'aggregation' => 'count'],
                ],
                'dimensions' => [
                    'id_cms_privileges' => 'Ruolo (id privilegio)',
                    'status' => 'Stato',
                    'created_at:month' => 'Mese di creazione',
                    'created_at:month_of_year' => 'Mese dell\'anno di creazione',
                    'created_at:day' => 'Giorno di creazione',
                ],
                'filters' => [
                    'status' => ['label' => 'Stato', 'type' => 'text'],
                    'id_cms_privileges' => ['label' => 'Ruolo (id privilegio)', 'type' => 'numeric'],
                ],
            ],
            'system_activity' => [
                'label' => 'Attività di sistema (log accessi)',
                'table' => 'cms_logs',
                'metrics' => [
                    'count' => ['label' => 'Numero eventi', 'column' => 'id', 'aggregation' => 'count'],
                ],
                'dimensions' => [
                    'id_cms_users' => 'Utente',
                    'created_at:day' => 'Giorno',
                    'created_at:month' => 'Mese',
                    'created_at:month_of_year' => 'Mese dell\'anno',
                ],
                'filters' => [
                    'id_cms_users' => ['label' => 'Utente', 'type' => 'numeric'],
                ],
            ],
        ];
    }

    /**
     * Un dataset per ogni tabella reale del DB non esclusa dalle regole
     * di sicurezza sopra, con metriche/dimensioni/filtri dedotti dal tipo
     * delle colonne (introspezione via information_schema).
     */
    private static function autoGenerated(): array
    {
        $curatedTables = array_column(self::curated(), 'table');
        $out = [];

        foreach (self::allowedTables() as $table) {
            if (in_array($table, $curatedTables, true)) {
                // Gia' coperta da un dataset scritto a mano sopra: quello
                // resta la versione "benedetta", niente doppione qui.
                continue;
            }

            $columns = self::allowedColumns($table);
            if (!$columns) {
                continue;
            }

            $out['table:' . $table] = [
                'label' => 'Tabella: ' . self::humanizeName($table, stripPrefix: true),
                'table' => $table,
                'metrics' => self::buildMetrics($columns),
                'dimensions' => self::buildDimensions($columns),
                'filters' => self::buildFilters($columns),
            ];
        }

        return $out;
    }

    /**
     * @return string[] nomi tabella (solo BASE TABLE, mai viste) del DB
     *                   corrente, gia' filtrati dalle regole di sicurezza.
     */
    private static function allowedTables(): array
    {
        $rows = DB::select(
            "SELECT TABLE_NAME AS name FROM information_schema.tables
             WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE'
             ORDER BY TABLE_NAME"
        );

        $tables = [];
        foreach ($rows as $row) {
            $name = $row->name;
            if (!self::isSafeIdentifier($name) || in_array($name, self::TABLE_DENYLIST, true)) {
                continue;
            }
            if (str_starts_with($name, 'cms_') && !in_array($name, self::CMS_TABLE_ALLOWLIST, true)) {
                continue;
            }
            $tables[] = $name;
        }

        return $tables;
    }

    /**
     * @return array<string, string> nome colonna => tipo MySQL (es. 'int',
     *                                'varchar', 'decimal', 'datetime'),
     *                                gia' filtrate dalla column denylist.
     */
    private static function allowedColumns(string $table): array
    {
        $rows = DB::select(
            'SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM information_schema.columns
             WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?
             ORDER BY ORDINAL_POSITION',
            [$table]
        );

        $columns = [];
        foreach ($rows as $row) {
            if (!self::isSafeIdentifier($row->name) || self::isDeniedColumn($row->name)) {
                continue;
            }
            $columns[$row->name] = $row->type;
        }

        return $columns;
    }

    private static function isDeniedColumn(string $column): bool
    {
        $lower = strtolower($column);
        foreach (self::COLUMN_DENYLIST_PATTERNS as $pattern) {
            if (str_contains($lower, $pattern)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Solo lettere/cifre/underscore: gli identificatori che finiscono
     * dentro selectRaw()/groupByRaw() in execute() passano sempre da qui
     * prima - un nome tabella/colonna che la CREATE TABLE di MySQL ha gia'
     * accettato non dovrebbe mai fallire questo controllo, e' una difesa
     * in profondita' aggiuntiva, non l'unica.
     */
    private static function isSafeIdentifier(string $name): bool
    {
        return (bool) preg_match('/^[A-Za-z0-9_]+$/', $name);
    }

    /**
     * "Conteggio righe" (sempre presente, sulla colonna id/prima colonna)
     * piu' Somma/Media/Minimo/Massimo per ogni colonna numerica del
     * dataset (docs/refactoring/138-*, punto 1 - erano gia' presenti
     * prima di 133, che le aveva tolte "finche' non fosse servito altro":
     * ora servono per i KPI su importi/quantita' discussi con l'utente,
     * es. "Fatturato totale"/"Incassato" su `mg_fatture.importo`).
     *
     * @param array<string, string> $columns nome colonna => tipo
     */
    private static function buildMetrics(array $columns): array
    {
        $pkColumn = array_key_exists('id', $columns) ? 'id' : array_key_first($columns);

        $metrics = [
            'count' => ['label' => 'Conteggio righe', 'column' => $pkColumn, 'aggregation' => 'count'],
        ];

        foreach ($columns as $name => $type) {
            if (self::columnTypeCategory($type) !== 'numeric') {
                continue;
            }
            $columnLabel = self::humanizeName($name);
            foreach (self::NUMERIC_METRIC_AGGREGATIONS as $aggregation => $aggregationLabel) {
                $metrics["{$aggregation}:{$name}"] = [
                    'label' => "{$aggregationLabel} {$columnLabel}",
                    'column' => $name,
                    'aggregation' => $aggregation,
                    // Label della sola colonna (senza il prefisso
                    // dell'aggregazione), usata da optionsForFrontend()
                    // per popolare la select "Colonna" separata dalla
                    // select "Funzione" (docs/refactoring/140) - senza
                    // salvarla qui andrebbe ricavata lato JS spezzando la
                    // label completa, fragile rispetto a tenerla gia'
                    // pronta qui dove viene generata.
                    'column_label' => $columnLabel,
                ];
            }
        }

        return $metrics;
    }

    /**
     * Categoria di una colonna (numeric/date/text) usata sia per decidere
     * quali metriche generare (buildMetrics()) sia quali operatori di
     * filtro offrire (buildFilters(), OPERATORS_BY_TYPE) - stessa
     * classificazione in entrambi i punti, un solo posto da aggiornare se
     * in futuro cambiasse.
     */
    private static function columnTypeCategory(string $mysqlType): string
    {
        if (in_array($mysqlType, self::DATE_TYPES, true)) {
            return 'date';
        }
        if (in_array($mysqlType, self::NUMERIC_TYPES, true)) {
            return 'numeric';
        }

        return 'text';
    }

    /**
     * @param array<string, string> $columns nome colonna => tipo
     * @return array<string, string>
     */
    private static function buildDimensions(array $columns): array
    {
        $dimensions = [];
        foreach ($columns as $name => $type) {
            $label = self::humanizeName($name);
            if (in_array($type, self::DATE_TYPES, true)) {
                // Raggruppare per il valore esatto di una data/ora non
                // avrebbe senso (quasi ogni riga finirebbe nel suo gruppo):
                // solo le viste aggregate giorno/mese/anno (docs/refactoring/151),
                // stesso standard dei dataset curati sopra.
                foreach (self::DATE_DIMENSION_FORMATS as $format => $formatLabelKey) {
                    $dimensions["{$name}:{$format}"] = "{$label} (" . trans($formatLabelKey) . ')';
                }
            } else {
                $dimensions[$name] = $label;
            }
        }

        return $dimensions;
    }

    /**
     * @param array<string, string> $columns nome colonna => tipo
     * @return array<string, array{label: string, type: string}>
     */
    private static function buildFilters(array $columns): array
    {
        $filters = [];
        foreach ($columns as $name => $type) {
            $filters[$name] = [
                'label' => self::humanizeName($name),
                'type' => self::columnTypeCategory($type),
            ];
        }

        return $filters;
    }

    private static function humanizeName(string $name, bool $stripPrefix = false): string
    {
        if ($stripPrefix) {
            // "mg_" (Module Generator) e "cms_" comparirebbero in ogni
            // singola etichetta altrimenti - tolti solo per la label
            // mostrata all'utente, mai dal nome tabella usato nella query.
            $name = preg_replace('/^(mg_|cms_)/', '', $name);
        }

        return ucfirst(str_replace('_', ' ', $name));
    }

    public static function get(string $key): ?array
    {
        return self::all()[$key] ?? null;
    }

    /**
     * Forma pensata per l'endpoint 'dataset-options' (popola le select del
     * builder guidato in sidebar). Ordine alfabetico per label (non
     * l'ordine "curati prima" di all()): con decine di tabelle la select
     * va cercata per nome, non scorsa in un ordine implicito.
     */
    public static function optionsForFrontend(): array
    {
        $out = [];
        $moduleTables = array_flip(DatasetAccessScope::moduleTables());
        foreach (self::all() as $key => $dataset) {
            $out[] = [
                'key' => $key,
                'label' => $dataset['label'],
                'metrics' => collect($dataset['metrics'])
                    ->map(fn ($m, $k) => ['key' => $k, 'label' => $m['label']])->values()->all(),
                // 'metric_functions'/'metric_columns' (docs/refactoring/140):
                // stessa lista di 'metrics' sopra scomposta in due, per il
                // pannello che ora sceglie Funzione e Colonna separatamente
                // invece di un'unica select con ogni combinazione gia'
                // composta (es. "Somma Importo") - config[metric] salvato
                // resta pero' lo stesso identico formato di sempre
                // ("count" o "aggregazione:colonna"), ricomposto lato JS
                // dalle due select: zero cambi qui sotto in execute().
                'metric_functions' => self::metricFunctionOptions($dataset['metrics']),
                'metric_columns' => self::metricColumnOptions($dataset['metrics']),
                'dimensions' => collect($dataset['dimensions'])
                    ->map(fn ($label, $k) => ['key' => $k, 'label' => $label])->values()->all(),
                // 'dimension_columns'/'dimension_formats' (docs/refactoring/151):
                // stessa lista di 'dimensions' sopra scomposta in due, per
                // il pannello che sceglie Colonna e (solo se la colonna e'
                // una data) Formato separatamente invece di un'unica select
                // con ogni combinazione gia' composta (es. "Creato il
                // (mese)") - config[group_by] salvato resta lo stesso
                // identico formato di sempre ("colonna" o
                // "colonna:formato"), ricomposto lato JS dalle due select.
                'dimension_columns' => self::dimensionColumnOptions($dataset['dimensions']),
                'dimension_formats' => self::dimensionFormatOptions(),
                'filters' => collect($dataset['filters'])
                    ->map(fn ($meta, $k) => ['key' => $k, 'label' => $meta['label'], 'type' => $meta['type']])->values()->all(),
                // Widget Tabella "Elenco record" (docs/piano-widget-tabella-
                // elenco-record.md): solo i dataset di tabelle mg_* con un
                // modulo attivo (stessa regola di executeRows()) offrono la
                // scelta delle colonne - per gli altri la modalita' non e'
                // selezionabile.
                'records' => isset($moduleTables[$dataset['table']]),
            ];
        }

        usort($out, fn ($a, $b) => strcasecmp($a['label'], $b['label']));

        return $out;
    }

    /**
     * Elenco delle funzioni di aggregazione disponibili per un dataset
     * (una per ogni 'aggregation' distinta tra le sue metriche, incluso
     * 'count') - i dataset curati a mano che definiscono solo 'count'
     * (es. `admin_users`) restituiscono cosi' un'unica funzione, niente
     * Somma/Media/Minimo/Massimo che per loro non esistono.
     *
     * @param array<string, array{label: string, column: string, aggregation: string}> $metrics
     * @return array<int, array{key: string, label: string}>
     */
    private static function metricFunctionOptions(array $metrics): array
    {
        $functions = [];
        foreach ($metrics as $metric) {
            $aggregation = $metric['aggregation'];
            if (!isset($functions[$aggregation])) {
                $functions[$aggregation] = $aggregation === 'count'
                    ? 'Conteggio righe'
                    : (self::NUMERIC_METRIC_AGGREGATIONS[$aggregation] ?? ucfirst($aggregation));
            }
        }

        return collect($functions)->map(fn ($label, $key) => ['key' => $key, 'label' => $label])->values()->all();
    }

    /**
     * Elenco delle colonne numeriche disponibili per l'aggregazione (le
     * stesse per qualunque funzione tra Somma/Media/Minimo/Massimo -
     * buildMetrics() le genera tutte e quattro per ogni colonna numerica,
     * quindi una sola lista basta per qualunque funzione scelta). 'count'
     * non compare mai qui: non ha bisogno di una colonna scelta
     * dall'utente (aggrega sempre sulla PK, vedi buildMetrics()).
     *
     * @param array<string, array{label: string, column: string, aggregation: string, column_label?: string}> $metrics
     * @return array<int, array{key: string, label: string}>
     */
    private static function metricColumnOptions(array $metrics): array
    {
        $columns = [];
        foreach ($metrics as $metric) {
            if ($metric['aggregation'] === 'count' || !isset($metric['column_label'])) {
                continue;
            }
            $columns[$metric['column']] = $metric['column_label'];
        }

        return collect($columns)->map(fn ($label, $key) => ['key' => $key, 'label' => $label])->values()->all();
    }

    /**
     * Elenco delle colonne disponibili per il raggruppamento, una per
     * colonna reale (non una per combinazione colonna:formato) - le
     * colonne data/datetime/timestamp hanno sempre tre voci in
     * `$dimensions` (una per formato, vedi buildDimensions()), qui
     * compaiono una sola volta con `type: 'date'` cosi' il pannello sa
     * quando mostrare la select "Formato" accanto. Le colonne non-data
     * hanno gia' una sola voce in `$dimensions` (`type: 'text'`, il
     * raggruppamento e' sempre sul valore esatto).
     *
     * @param array<string, string> $dimensions chiave "colonna" o "colonna:formato" => etichetta
     * @return array<int, array{key: string, label: string, type: string}>
     */
    private static function dimensionColumnOptions(array $dimensions): array
    {
        $columns = [];
        foreach (array_keys($dimensions) as $key) {
            $isDate = str_contains($key, ':');
            $column = $isDate ? explode(':', $key, 2)[0] : $key;
            if (!isset($columns[$column])) {
                // Rietichettata da zero sul nome colonna (non spezzando la
                // label gia' composta in $dimensions, es. "Creato il
                // (mese)") - stessa humanizeName() usata per generarla.
                $columns[$column] = ['label' => self::humanizeName($column), 'type' => $isDate ? 'date' : 'text'];
            }
        }

        return collect($columns)->map(fn ($meta, $key) => ['key' => $key, 'label' => $meta['label'], 'type' => $meta['type']])->values()->all();
    }

    /**
     * Le granularita' offerte per una colonna data (Giorno/Mese/Anno,
     * docs/refactoring/151) - sempre le stesse per qualunque dataset,
     * esposte comunque per dataset (come metric_functions/metric_columns)
     * per coerenza con la forma che il pannello si aspetta.
     *
     * @return array<int, array{key: string, label: string}>
     */
    private static function dimensionFormatOptions(): array
    {
        return collect(self::DATE_DIMENSION_FORMATS)->map(fn ($labelKey, $key) => ['key' => $key, 'label' => trans($labelKey)])->values()->all();
    }

    /**
     * Esegue un dataset con i parametri scelti nel builder guidato e
     * restituisce sempre righe {label, value}: senza 'group_by' una sola
     * riga (il valore aggregato, usato dal widget KPI), con 'group_by' una
     * riga per gruppo (usato da grafici e tabella).
     *
     * @param array{metric?: string, group_by?: string|null, filters?: array<string,mixed>} $params
     * @return array<int, array{label: string, value: float|int|string}>
     *
     * @throws \InvalidArgumentException se dataset/metrica/group_by/filtro non sono nella whitelist
     */
    public static function execute(string $datasetKey, array $params): array
    {
        $dataset = self::get($datasetKey);
        if (!$dataset) {
            throw new \InvalidArgumentException("Dataset sconosciuto: {$datasetKey}");
        }

        $metricKey = $params['metric'] ?? array_key_first($dataset['metrics']);
        $metric = $dataset['metrics'][$metricKey] ?? null;
        if (!$metric) {
            throw new \InvalidArgumentException("Metrica sconosciuta: {$metricKey}");
        }

        $groupBy = $params['group_by'] ?? null;
        if ($groupBy && !isset($dataset['dimensions'][$groupBy])) {
            throw new \InvalidArgumentException("Raggruppamento non consentito: {$groupBy}");
        }

        $query = DB::table($dataset['table']);

        foreach (self::normalizeFilters($params['filters'] ?? []) as $filter) {
            $column = $filter['column'];
            if (!isset($dataset['filters'][$column])) {
                throw new \InvalidArgumentException("Filtro non consentito: {$column}");
            }

            self::applyFilter($query, $column, $filter['operator'], $filter['value'], $dataset['filters'][$column]['type']);
        }

        $metricExpr = "{$metric['aggregation']}({$metric['column']})";

        if (!$groupBy) {
            $row = $query->selectRaw("{$metricExpr} as value")->first();

            return [['label' => $metric['label'], 'value' => $row->value ?? 0]];
        }

        [$groupColumn, $groupModifier] = array_pad(explode(':', $groupBy, 2), 2, null);
        $groupExpr = match ($groupModifier) {
            'month' => "DATE_FORMAT({$groupColumn}, '%Y-%m')",
            'month_of_year' => "DATE_FORMAT({$groupColumn}, '%m')",
            'day' => "DATE_FORMAT({$groupColumn}, '%Y-%m-%d')",
            'year' => "DATE_FORMAT({$groupColumn}, '%Y')",
            default => $groupColumn,
        };

        $rows = $query
            ->selectRaw("{$groupExpr} as label, {$metricExpr} as value")
            ->groupByRaw($groupExpr)
            ->orderByRaw($groupExpr)
            ->limit(50)
            ->get();

        return $rows->map(fn ($r) => ['label' => (string) $r->label, 'value' => $r->value])->all();
    }

    /**
     * Tetto fisso di righe restituite da executeRows() (widget Tabella
     * "Elenco record", docs/piano-widget-tabella-elenco-record.md): la
     * paginazione e' lato client, quindi il server non manda mai piu' di
     * cosi'.
     */
    public const ROWS_MAX_LIMIT = 500;

    /** Valori ammessi per "record per pagina" (lunghezza iniziale di pagina DataTables). */
    public const ROWS_PAGE_LENGTHS = [10, 25, 50, 100];

    /**
     * Elenco di righe vere (non aggregati) di una tabella `mg_*` per il
     * widget Tabella "Elenco record". A differenza di execute(), applica
     * SEMPRE lo scoping dell'utente corrente (DatasetAccessScope): i dati
     * sono righe grezze, non somme, quindi tenant/gruppi contano.
     *
     * Ordine di applicazione: accesso al dataset -> scoping utente ->
     * filtri del widget in AND. I filtri non sostituiscono mai la sicurezza.
     * Colonne, order_by e filtri sono riverificati contro la whitelist del
     * dataset a ogni chiamata (mai fidarsi della config salvata).
     *
     * @param array{columns?: string[], filters?: mixed, order_by?: string|null, order_dir?: string, limit?: int} $params
     * @return array{columns: array<string, string>, rows: array<int, array<string, mixed>>}
     *         `columns`: nome colonna => etichetta, nell'ordine richiesto.
     *
     * @throws \InvalidArgumentException dataset non ammesso o colonna/ordinamento/filtro fuori whitelist
     * @throws \Illuminate\Auth\Access\AuthorizationException se l'utente non puo' leggere la tabella
     */
    public static function executeRows(string $datasetKey, array $params): array
    {
        $dataset = self::get($datasetKey);
        if (!$dataset) {
            throw new \InvalidArgumentException("Dataset sconosciuto: {$datasetKey}");
        }

        $table = $dataset['table'];
        if (!ModuleHelper::is_manually_generated($table) || !DatasetAccessScope::hasModule($table)) {
            throw new \InvalidArgumentException("Dataset non ammesso per l'elenco record: {$datasetKey}");
        }
        if (!DatasetAccessScope::canRead($table)) {
            throw new \Illuminate\Auth\Access\AuthorizationException("Accesso negato alla tabella: {$table}");
        }

        // Whitelist colonne = le colonne di 'filters' (tutte quelle
        // ammesse, gia' senza denylist credenziali, vedi allowedColumns()).
        $allowed = $dataset['filters'];

        $requested = array_values(array_unique((array) ($params['columns'] ?? [])));
        if (!$requested) {
            throw new \InvalidArgumentException('Nessuna colonna selezionata.');
        }
        $columns = [];
        foreach ($requested as $column) {
            if (!is_string($column) || !isset($allowed[$column])) {
                throw new \InvalidArgumentException('Colonna non consentita: ' . (is_string($column) ? $column : gettype($column)));
            }
            $columns[$column] = $allowed[$column]['label'];
        }

        $orderBy = $params['order_by'] ?? null;
        if ($orderBy !== null && $orderBy !== '' && !isset($allowed[$orderBy])) {
            throw new \InvalidArgumentException("Ordinamento non consentito: {$orderBy}");
        }
        $orderDir = strtolower((string) ($params['order_dir'] ?? 'asc'));
        if (!in_array($orderDir, ['asc', 'desc'], true)) {
            throw new \InvalidArgumentException("Direzione di ordinamento non valida: {$orderDir}");
        }

        $limit = (int) ($params['limit'] ?? self::ROWS_MAX_LIMIT);
        $limit = max(1, min($limit, self::ROWS_MAX_LIMIT));

        $query = DB::table($table);

        if (Schema::hasColumn($table, 'deleted_at')) {
            $query->whereNull($table . '.deleted_at');
        }

        DatasetAccessScope::applyRowScope($query, $table);

        foreach (self::normalizeFilters($params['filters'] ?? []) as $filter) {
            $column = $filter['column'];
            if (!isset($allowed[$column])) {
                throw new \InvalidArgumentException("Filtro non consentito: {$column}");
            }
            self::applyFilter($query, $column, $filter['operator'], $filter['value'], $allowed[$column]['type']);
        }

        $query->select(array_map(fn ($c) => $table . '.' . $c, array_keys($columns)));

        if ($orderBy) {
            $query->orderBy($table . '.' . $orderBy, $orderDir);
        } elseif (isset($allowed['id'])) {
            $query->orderBy($table . '.id', 'desc');
        }

        $rows = $query->limit($limit)->get()->map(fn ($r) => (array) $r)->all();

        return ['columns' => $columns, 'rows' => $rows];
    }

    /**
     * Normalizza `config->filters` in una lista di
     * `{column, operator, value}`, accettando sia il formato nuovo (lista
     * di oggetti, un filtro per riga del pannello - docs/refactoring/138)
     * sia quello vecchio (mappa `colonna => valore`, sempre uguaglianza -
     * unico formato salvabile prima di 138, ancora presente sui widget
     * gia' configurati). Pubblico: riusato anche da
     * `_query_builder_fields.blade.php` per precompilare le righe del
     * pannello con i filtri gia' salvati, stessa logica in un solo posto.
     *
     * Distinzione tra i due formati: il nuovo e' sempre una lista
     * (`array_is_list`) di elementi con una chiave 'column' - una mappa
     * `colonna => valore` scritta a mano non lo e' quasi mai (le chiavi
     * sono nomi di colonna, non indici 0..n-1) e i suoi valori sono
     * scalari, non oggetti/array con 'column' dentro.
     *
     * @param mixed $raw
     * @return array<int, array{column: string, operator: string, value: mixed}>
     */
    public static function normalizeFilters(mixed $raw): array
    {
        $raw = (array) $raw;
        if (!$raw) {
            return [];
        }

        $first = (array) reset($raw);
        $isNewFormat = array_is_list($raw) && array_key_exists('column', $first);

        $normalized = [];

        if ($isNewFormat) {
            foreach ($raw as $entry) {
                $entry = (array) $entry;
                $column = $entry['column'] ?? null;
                $value = $entry['value'] ?? null;
                if (!$column || $value === null || $value === '') {
                    continue;
                }
                $normalized[] = [
                    'column' => $column,
                    'operator' => $entry['operator'] ?? '=',
                    'value' => $value,
                ];
            }
        } else {
            foreach ($raw as $column => $value) {
                if ($value === null || $value === '') {
                    continue;
                }
                $normalized[] = ['column' => (string) $column, 'operator' => '=', 'value' => $value];
            }
        }

        return $normalized;
    }

    /**
     * Applica un singolo filtro alla query, validando l'operatore contro
     * OPERATORS_BY_TYPE per la categoria della colonna (mai fidarsi
     * dell'operatore scelto lato client, anche se la UI mostra solo
     * quelli "adatti" al tipo). 'contains' (solo testo) usa LIKE con % e
     * _ del valore letterale escapati (altrimenti un valore utente tipo
     * "50%" verrebbe interpretato come wildcard invece che testo
     * letterale). 'last_days' (solo data) confronta con
     * `DATE_SUB(CURDATE(), INTERVAL N DAY)`: N e' sempre castato a intero
     * positivo prima di finire in una DB::raw(), altrimenti un valore
     * malformato finirebbe interpolato senza binding nella query.
     */
    private static function applyFilter(Builder $query, string $column, string $operator, mixed $value, string $columnType): void
    {
        $allowedOperators = self::OPERATORS_BY_TYPE[$columnType] ?? self::OPERATORS_BY_TYPE['text'];
        if (!in_array($operator, $allowedOperators, true)) {
            throw new \InvalidArgumentException("Operatore non consentito per {$column}: {$operator}");
        }

        if ($operator === 'contains') {
            $escaped = addcslashes((string) $value, '%_\\');
            $query->where($column, 'like', '%' . $escaped . '%');

            return;
        }

        if ($operator === 'last_days') {
            $days = (int) $value;
            if ($days < 1) {
                throw new \InvalidArgumentException("Numero di giorni non valido per {$column}: {$value}");
            }
            $query->where($column, '>=', DB::raw("DATE_SUB(CURDATE(), INTERVAL {$days} DAY)"));

            return;
        }

        // '=', '!=', '>', '<', '>=', '<=': operatore di confronto diretto,
        // valore sempre passato per binding (mai interpolato). Validato
        // PRIMA di finire nella query (docs/refactoring/153-*, segnalato
        // dall'utente): senza questo controllo un valore del tipo
        // sbagliato per la colonna (es. una data su una colonna numerica
        // come "creato da") non dava alcun errore - MySQL confronta con
        // una conversione implicita silenziosa, producendo un risultato
        // vuoto o sbagliato invece di un errore comprensibile.
        self::validateFilterValue($column, $value, $columnType);
        $query->where($column, $operator, $value);
    }

    /**
     * Verifica che il valore di un filtro sia del formato atteso per il
     * tipo della colonna, prima di lasciarlo entrare in un confronto
     * diretto (=/!=/>/</>=/<=) - non per 'contains' (qualunque testo va
     * bene) ne' per 'last_days' (gia' validato a parte, e' un numero di
     * giorni non una data).
     */
    private static function validateFilterValue(string $column, mixed $value, string $columnType): void
    {
        if ($columnType === 'numeric' && !is_numeric($value)) {
            throw new \InvalidArgumentException("Il filtro su '{$column}' richiede un valore numerico, non \"{$value}\".");
        }

        if ($columnType === 'date' && !preg_match('/^\d{4}-\d{2}-\d{2}([ T]\d{2}:\d{2}(:\d{2})?)?$/', (string) $value)) {
            throw new \InvalidArgumentException("Il filtro su '{$column}' richiede una data nel formato AAAA-MM-GG, non \"{$value}\".");
        }
    }
}
